### ISSUE TITLE
Question: Will there be a merge of updates from the original NukkitX 1.0?

### ISSUE THREAD

**Issue by AntonPPDS** [GameModsBR/PowerNukkit#213]
For example 1.14.60 support, new events etc.

**Comment by Htepple** [comment]
hah

**Comment by joserobjr** [comment]
Yes, I'm prioritizing some other projects due to some business needs, but I'm going to schedule a time to keep PowerNukkit 1.X up to date since there are some awesome people interacting with the project.

Don't use PowerNukkit 2.0 yet, it still needs a lot of work. When it becomes ready you will be able to convert PowerNukkit 1.X, NukkitX 1.X to PowerNukkit 2.0, and we are planning to keep 2.X compatible to NukkitX 2.X levels in both ways.
