### ISSUE TITLE
Compatibility of some enchantments are wrong 

### ISSUE THREAD

**Issue by AntonPPDS** [GameModsBR/PowerNukkit#237]
When I talk about compatibility, I mean compatibility with item and other enchantments. Some of them are set incorrectly. Here are the ones I personally found:

- https://github.com/GameModsBR/PowerNukkit/blob/master/src/main/java/cn/nukkit/item/enchantment/EnchantmentThorns.java#L17 (incorrect EnchantmentType)
- https://github.com/GameModsBR/PowerNukkit/blob/master/src/main/java/cn/nukkit/item/enchantment/EnchantmentDurability.java#L33 (it's not "not compatible with Fortune")

Affected version: https://github.com/GameModsBR/PowerNukkit/commit/a8316567b28f7282ceee94a767d952928ec9add8

**Comment by joserobjr** [comment]
Just a note:
https://github.com/GameModsBR/PowerNukkit/blob/5fda421693ced17773be4baed583e2cf02965298/src/main/java/cn/nukkit/item/enchantment/EnchantmentThorns.java#L20-L22

The `ARMOR_TORSO` is actually right because it's related to the enchantment table, the "Primary Item" column in https://minecraft.gamepedia.com/Enchanting#Summary_of_enchantments

The anvil uses primary item + secondary item. The secondary item logic is now implemented.
