### ISSUE TITLE
Hi! Just asking

### ISSUE THREAD

**Issue by NycuRO** [GameModsBR/PowerNukkit#245]
# 🤷‍♀️ I have a question

Why creating a fork instead of contributing on nukkit itself or contributing to nukkit 2.0 to make it a great software on java? :)
Still a lot of guys are contributing on 2.0 and i see you have a lot of potential and you are good. What about trying to contribute you too? :)

**Comment by joserobjr** [comment]
Hi, I needed Nukkit to support new blocks, items and game features in 1.X, when 2.0 source wasn't public. To achieve that I had to modify how Nukkit saves the world a little, making the chunks incompatible with the original Nukkit when it contains a new block or any waterlogged block. I knew that such changes would not be welcome by NukkitX team but I tried to submit a PR to them anyway: https://github.com/NukkitX/Nukkit/pull/1022 

Although other people liked, it was silently rejected:
![image](https://user-images.githubusercontent.com/3679022/81506773-1b2c6000-92cf-11ea-99be-f9950040b2ad.png)

It wasn't a surprise for me because I was already expecting something like that and I would also keep my own fork anyway because it is easier for me when I need to change something quicker for my network, so I kept my fork and to avoid causing trouble to NukkitX due to users using my version instead of the official, I renamed it to PowerNukkit and flagged the versions so they could quickly identify reported issues which doesn't have their original code and redirect the issue to here.

Later, the 2.0 branch were published, so I called my organization contributors to help migrating everything to 2.0 since merging our master to the new 2.0 branch was way hard and was causing a lot of errors. It was easier and safer to manually migrate everything. In the process I tried to send the migrated features to NukkitX 2.0's branch sending one feature by PR, this worked and almost everything got accepted. Right now almost all stuff that we have in our 2.X branch is in NukkitX, we are trying to keep PowerNukkit 2.X level format fully compatible with NukkitX 2.X.

I also merged a lot of nice NukkitX pull requests which were being ignored or kept on hold there, the new raknet and more redstone component PR are good examples.

An other difference is that I'm organizing every change using semantic versioning and a proper change log, this makes sure that PowerNukkit consumers knows what is being changed and if an update would break some API or not, it also makes easier for plugin devs to specify the minimum PowerNukkit version for the plugin to work.

I stopped sending PRs to NukkitX recently because I had some personal problems which I had to deal with and I also had to prioritize some other stuffs in our organizations, so I got fewer time available for bedrock edition development, so I spent my time developing PowerNukkit. Sending PRs to NukkitX 1.X requires more effort then 2.X because it's harder to get accepted and because I would have to cherrypick, adjust and retest everything only for NukkitX because our 1.X implementation differs from NukkitX. 2.X changes are easier because they are more in sync with NukkitX.

Our 2.X branches are also outdated right now because of our reprioritization but we have an open task to update them all.

**Comment by NycuRO** [comment]
Hello. Thanks for answer. The things you maked for 1.0 was kinda hacky and that's why them are rejected. Those was maked on 2.0 branch already which is public *me, to be honest, and others*, respected your work so much. It's your deccision if you want to not contribute anymore, but my suggest it's to contribute on 2.0 branch because 1.0 it's just going to updated for new versions, not for new addons on it. 2.0 it's the priority for now and we really respect people who want to help to 2.0.

I hope to come back to us and work for 2.0. Let 1.0 go, it's updated only for version, 2.0 it's priority.

Redstone and the others was not implemented already because them are not finished.

**Comment by joserobjr** [comment]
Thank you @NycuRO . I will continue to contribute to NukkitX 2.0, but I at this time I need 1.X to be working well with the new stuff

**Comment by MrRazamataz** [comment]
So say I'm using PowerNukkit now, if I wanted to switch to Nukkit 2.0, would the world be fully compatible and would the only thing I would need to change be the plugins?

**Comment by tuilakhanh** [comment]
> So say I'm using PowerNukkit now, if I wanted to switch to Nukkit 2.0, would the world be fully compatible and would the only thing I would need to change be the plugins?

Sloved #288

**Comment by joserobjr** [comment]
If you are using PowerNukkit 1.X you would need to upgrade to PowerNukkit 2.X first (when it's ready), so the world would be correctly upgraded and then you could switch to NukkitX 2.X with less impact.

We are trying to keep PowerNukkit 2.X world-compatible with NukkitX 2.X. 

NukkitX (both 1.X and 2.X) does not support PowerNukkit 1.X worlds, we have made some effort to reduce impacts if you decide to switch back to NukkitX 1.X later but chunks which uses new stuff (like blocks with high id or waterlogged blocks) might get some weird blocks or completely break and get reset.

**Comment by MrRazamataz** [comment]
Ok thank you.
